//
//  ModelData.swift
//  LeaderList
//
//  Created by user242876 on 8/3/23.
//

import Foundation
import CoreLocation

var leaders: [Leader] =
[
    Leader(name: "Joe Biden", age: 80, DOB: "20/11/1942", country: "USA", position: "President", description: "Joseph Robinette Biden Jr. is an American politician who is the 46th and current president of the United States. A member of the Democratic Party, he previously served as the 47th vice president from 2009 to 2017 under President Barack Obama and represented Delaware in the United States Senate from 1973 to 2009", imageName: "joe_biden", locationCoordinate: CLLocationCoordinate2D(latitude: 38.897678 , longitude: -77.036551)),
    
    Leader(name: "Rishi Sunak", age: 43, DOB: "12/05/1980", country: "United Kingdom", position: "Prime Minister", description: "Rishi Sunak is a British politician who has served as Prime Minister of the United Kingdom and Leader of the Conservative Party since 2022. He is the first British Asian prime minister. He previously held two cabinet positions under Boris Johnson, lastly as Chancellor of the Exchequer from 2020 to 2022.", imageName: "rishi_sunak", locationCoordinate: CLLocationCoordinate2D(latitude: 51.503547 , longitude: -0.127700)),
    
    Leader(name: "Alberto Fernandez", age: 64, DOB: "02/04/1959", country: "Argentina", position: "President", description: "Alberto Ángel Fernández is an Argentine politician, lawyer and professor, serving as president of Argentina since 2019. Born in Buenos Aires, Fernández attended the University of Buenos Aires, where he earned his law degree at the age of 24, and later became a professor of criminal law.", imageName: "alberto-fernandez", locationCoordinate: CLLocationCoordinate2D(latitude: -34.608204  ,longitude: -58.370243)),
    
    Leader(name: "Andres Manuel Lopez Obrador", age: 69, DOB: "13/11/1953", country: "Mexico", position: "President", description: "Andrés Manuel López Obrador, also known by his initials AMLO, is a Mexican politician who has been serving as the 65th president of Mexico since 1 December 2018. He previously served as Head of Government of Mexico City from 2000 to 2005.", imageName: "andres-manuel", locationCoordinate: CLLocationCoordinate2D(latitude: 19.432590,  longitude: -99.131860)),

    Leader(name: "Anthony Albanese", age: 60, DOB: "02/03/1963", country: "Australia", position: "Prime Minister", description: "Anthony Norman Albanese is an Australian politician serving as the 31st and current prime minister of Australia since 2022. He has been leader of the Australian Labor Party since 2019 and the member of parliament for Grayndler since 1996", imageName: "anthony_albanese", locationCoordinate: CLLocationCoordinate2D(latitude: -35.308167,  longitude: 149.124510)),

    Leader(name: "Antonio Costa", age: 62, DOB: "17/07/1961", country: "Portugal", position: "Prime Minister", description: "António Luís Santos da Costa GCIH is a Portuguese lawyer and politician who has served as the 119th and current prime minister of Portugal since 26 November 2015, presiding over the XXI, XXII and XXIII Constitutional Governments.", imageName: "antonio_costa", locationCoordinate: CLLocationCoordinate2D(latitude: 38.712481,  longitude: -9.153670)),
    
    
    
    Leader(name: "Arturs Krišjānis Kariņš", age: 58, DOB: "13/02/1964", country: "Latvia", position: "Prime Minister", description: "Arturs Krišjānis Kariņš is a Latvian-American politician who has served as the Prime Minister of Latvia since 2019. A linguist and businessman by profession, he previously served as Latvia's Minister of Economics and a Member of the European Parliament. ", imageName: "arturs_krisjanis", locationCoordinate: CLLocationCoordinate2D(latitude: 56.951111,  longitude: 24.104444)),

    Leader(name: "Chris Hipkins", age: 44, DOB: "05/09/1978", country: "New Zealand", position: "Prime Minister", description: "Christopher John Hipkins is a New Zealand politician who has been serving as the 41st prime minister of New Zealand and leader of the New Zealand Labour Party since 2023. He became member of Parliament for Remutaka in 2008.", imageName: "chris_hipkins", locationCoordinate: CLLocationCoordinate2D(latitude: -41.278396,  longitude: 174.776377)),

    Leader(name: "Emmanuel Macron", age: 45, DOB: "21/12/1977", country: "France", position: "President", description: "Emmanuel Jean-Michel Frédéric Macron, born 21 December 1977 in Amiens,is a French politician serving as the President of France since 2017. Ex officio, he is also one of the two Co-Princes of Andorra. Earlier, Macron served as the Minister of Economics, Industry and Digital Affairs under President François Hollande from 2014 to 2016 and Deputy Secretary-General to the President from 2012 to 2014.", imageName: "emmanuel_macron", locationCoordinate: CLLocationCoordinate2D(latitude: 48.870364,  longitude: 2.316758)),

    Leader(name: "Recep Tayyip Erdoğan", age: 69, DOB: "29/02/1954", country: "Turkey", position: "President", description: "Recep Tayyip Erdoğan is a Turkish politician serving as the 12th and current president of Turkey since 2014. He previously served as prime minister of Turkey from 2003 to 2014 and as mayor of Istanbul from 1994 to 1998. He also co-founded the Justice and Development Party in 2001.", imageName: "erdogan", locationCoordinate: CLLocationCoordinate2D(latitude: 39.930890,  longitude: 32.799024)),
    
    Leader(name: "Fumio Kishida", age: 66, DOB: "29/07/1957", country: "Japan", position: "Prime Minister", description: "Fumio Kishida is a Japanese politician serving as prime minister of Japan and president of the Liberal Democratic Party since 2021. A member of the House of Representatives, he previously served as Minister for Foreign Affairs from 2012 to 2017 and as acting Minister of Defense in 2017.", imageName: "fumio_kishida", locationCoordinate: CLLocationCoordinate2D(latitude: 35.673019,  longitude: 139.742422)),

    Leader(name: "Gitanas Nausėda", age: 59, DOB: "19/05/1964", country: "Lithuania", position: "President", description: "Gitanas Nausėda is a Lithuanian politician, economist and banker who is serving as the ninth and current president of Lithuania since 2019. He was previously director of monetary policy at the Bank of Lithuania from 1996 to 2000 and chief economist to the chairman of SEB bankas from 2008 to 2018.", imageName: "gitanas_nauseda", locationCoordinate: CLLocationCoordinate2D(latitude: 54.683115,  longitude: 25.286436)),
    
    

    Leader(name: "Hassanal Bolkiah", age: 70, DOB: "05/08/1952", country: "Brunei", position: "Sultan", description: "Hassanal Bolkiah ibni Omar Ali Saifuddien III is Sultan and Yang di-Pertuan of Brunei since 1967 and the Prime Minister of Brunei since independence from the United Kingdom in 1984. He is one of the few absolute monarchs in the world.", imageName: "hassanal_bolkiah", locationCoordinate: CLLocationCoordinate2D(latitude: 4.871519,  longitude: 114.921110)),

    Leader(name: "Hun Sen", age: 62, DOB: "17/07/1961", country: "Cambodia", position: "Prime Minister", description: "Samdech Hun Sen is a Cambodian politician and former military commander who has been the prime minister of Cambodia since 1985. He is the longest-serving head of government in Cambodia's history, and one of the longest-serving leaders in the world. ", imageName: "hun-sen", locationCoordinate: CLLocationCoordinate2D(latitude: 11.562122,  longitude: 104.916145)),

    Leader(name: "Joko Widodo", age: 62, DOB: "21/06/1961", country: "Indonesia", position: "President", description: "Joko Widodo, popularly known as Jokowi, is an Indonesian politician and businessman who is the seventh and current president of Indonesia. A member of the Indonesian Democratic Party of Struggle, he was the country's first president to not have emerged from the country's political or military elite.", imageName: "joko_widodo", locationCoordinate: CLLocationCoordinate2D(latitude: -6.170152,  longitude: 106.824157)),

    Leader(name: "Justin Trudeau", age: 51, DOB: "25/12/1971", country: "Canada", position: "Prime Minister", description: "Justin Pierre James Trudeau PC MP is a Canadian politician serving as the 23rd and current prime minister of Canada since 2015 and leader of the Liberal Party since 2013.", imageName: "justin_trudeau", locationCoordinate: CLLocationCoordinate2D(latitude: 45.423575,  longitude: -75.697227)),

    Leader(name: "Lula Da Silva", age: 62, DOB: "17/07/1961", country: "Brazil", position: "President", description: "Luiz Inácio Lula da Silva, also known as Lula da Silva or simply Lula, is a Brazilian politician who is the 39th and current president of Brazil. A member of the Workers' Party, he previously served as the 35th president of Brazil from 2003 to 2010.", imageName: "luiz_inacio", locationCoordinate: CLLocationCoordinate2D(latitude: -15.799047,  longitude: -47.860823)),

    Leader(name: "BongBong Marcos", age: 77, DOB: "27/10/1945", country: "Philipines", position: "President", description: "Ferdinand BongBong Romualdez Marcos Jr, born September 13, 1957, commonly referred to by the initials PBBM or BBM, is a Filipino politician who is the 17th and current president of the Philippines. Marcos is also the secretary of agriculture, holding the post in concurrent capacity. He previously served as a senator from 2010 to 2016. He is the second child and only son of 10th president and dictator Ferdinand Marcos Sr. and former first lady Imelda Romualdez Marcos.", imageName: "marcos-bongbong", locationCoordinate: CLLocationCoordinate2D(latitude: 14.593947,  longitude: 120.994349)),

    Leader(name: "Mohammed bin Salman", age: 37, DOB: "31/08/1985", country: "Saudia Arabia", position: "Crown Prince/Prime Minister", description: "Mohammed bin Salman Al Saud, colloquially known by his initials MBS or MbS, is crown prince and Prime Minister of Saudi Arabia. He also serves as the chairman of the Council of Economic and Development Affairs and chairman of the Council of Political and Security Affairs. He is considered the de facto ruler of Saudi Arabia, being deemed as such even before his appointment as prime minister in 2022. He served as minister of defense from 2015 to 2022. He is the seventh son of King Salman. He was named the 8th most powerful person in the world by Forbes. He has a reported personal wealth of at least $25 billion, making him one of the wealthiest royals and individuals in the world.", imageName: "MBS", locationCoordinate: CLLocationCoordinate2D(latitude: 24.662637,  longitude: 46.636549)),

    Leader(name: "Mette Frederiksen", age: 45, DOB: "19/11/1977", country: "Denmark", position: "Prime Minister", description: "Mette Frederiksen is a Danish politician who has served as Prime Minister of Denmark since June 2019, and Leader of the Social Democrats since June 2015. The second woman to hold either office, she is also the youngest prime minister in Danish history", imageName: "mette_frederiksen", locationCoordinate: CLLocationCoordinate2D(latitude: 55.675358,  longitude: 12.578015)),

    Leader(name: "Narendra Modi", age: 72, DOB: "17/09/1950", country: "India", position: "Prime Minister", description: "Narendra Damodardas Modi is an Indian politician who has served as the 14th Prime Minister of India since May 2014. Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament for Varanasi.", imageName: "nahendra-modi", locationCoordinate: CLLocationCoordinate2D(latitude: 28.615000,  longitude: 77.205833)),
    //continue
    
   
    Leader(name: "Olaf Scholz", age: 65, DOB: "14/06/1958", country: "Germany", position: "Chancellor", description: "Olaf Scholz is a German politician who has been serving as the chancellor of Germany since 8 December 2021. A member of the Social Democratic Party, he previously served as Vice Chancellor in the fourth Merkel cabinet and as Federal Minister of Finance from 2018 to 2021.", imageName: "olaf_scholz",locationCoordinate: CLLocationCoordinate2D(latitude: 52.520152,  longitude: 13.369128)),
    
    Leader(name: "Pedro Sanchez", age: 51, DOB: "29/02/1972", country: "Spain", position: "Prime Minister", description: "Pedro Sánchez Pérez-Castejón is a Spanish politician who has been Prime Minister of Spain since June 2018. He has also been Secretary-General of the Spanish Socialist Workers' Party since June 2017, having previously held that office from 2014 to 2016.", imageName: "pedro_sanchez", locationCoordinate: CLLocationCoordinate2D(latitude: 40.443663,  longitude: -3.737014)),
    
    Leader(name: "Pham Minh Chinh", age: 72, DOB: "10/12/1958", country: "Vietnam", position: "Prime Minister", description: "Phạm Minh Chính (born 10 December 1958) is a Vietnamese politician and public security general. He is the current Prime Minister of Vietnam, the third highest ranking after General Secretary of the Communist Party and the President of Vietnam. A member of the Politburo of the Communist Party since 2016, Chính is also the Vice Chairman of the National Defense and Security Council of Vietnam. He is a Member of the National Assembly of Vietnam and a Lieutenant General of the People's Public Security Forces.", imageName: "pham_minhchinh", locationCoordinate: CLLocationCoordinate2D(latitude: 21.039256,   longitude: 105.834458)),
    
    
    Leader(name: "Prayut Chan O Cha", age: 69, DOB: "21/03/1954", country: "Thailand", position: "Prime Minister", description: "Prayut Chan-o-cha is a Thai politician and army officer who has served as the Prime Minister of Thailand since he seized power in a military coup in 2014. He is concurrently the Minister of Defence, a position he has held in his own government since 2019. Prayut served as Commander-in-Chief of the Royal Thai Army from 2010 to 2014 and led the 2014 Thai coup d'état which installed the National Council for Peace and Order (NCPO), the military junta which governed Thailand between 22 May 2014 and 10 July 2019.", imageName: "prayut_chanocha", locationCoordinate: CLLocationCoordinate2D(latitude: 13.763060,  longitude: 100.512034)),
    
    Leader(name: "Ramaphosa", age: 70, DOB: "17/11/1952", country: "South Africa", position: "President", description: "Matamela Cyril Ramaphosa is a South African businessman and politician who is the fifth and current president of South Africa. A former anti-apartheid activist, trade union leader, and businessman, Ramaphosa is also the president of the African National Congress.", imageName: "ramaphosa", locationCoordinate: CLLocationCoordinate2D(latitude: -33.926109,  longitude: 18.420439)),
    
    Leader(name: "Tsai Ing Wen", age: 66, DOB: "31/08/1956", country: "Taiwan (Republic Of China)", position: "President", description: "Tsai Ing-wen is a Taiwanese politician who has served as the president of the Republic of China (Taiwan) since 2016. A member of the Democratic Progressive Party (DPP), Tsai is the first female president of Taiwan. She served as chair of the DPP from 2020 to 2022, and also previously from 2008 to 2012 and 2014 to 2018.", imageName: "tsai-ingwen", locationCoordinate: CLLocationCoordinate2D(latitude: 25.039955,  longitude: 121.511782)),
    
    Leader(name: "Ursula von der Leyen", age: 64, DOB: "08/10/1958", country: "European Union", position: "President of European Comssion", description: "Ursula Gertrud von der Leyen is a German physician and politician serving as the 13th president of the European Commission since 2019. She served in the German federal government between 2005 and 2019, holding successive positions in Angela Merkel's cabinet, most recently as minister of defence. Von der Leyen is a member of the centre-right Christian Democratic Union (CDU) and its EU affiliated group, the European People's Party (EPP).", imageName: "ursula_von_der_leyen", locationCoordinate: CLLocationCoordinate2D(latitude: 50.843566,  longitude: 4.382170)),
    
    Leader(name: "Vladimir Putin", age: 70, DOB: "07/10/1952", country: "Russia", position: "President", description: "Vladimir Vladimirovich Putin is a Russian politician and former intelligence officer serving as the current president of Russia. Putin has served continuously as president or prime minister since 1999: as prime minister from 1999 to 2000 and from 2008 to 2012, and as president from 2000 to 2008 and since 2012.", imageName: "vladimir-putin", locationCoordinate: CLLocationCoordinate2D(latitude: 55.751495,  longitude: 37.618153)),
    
    Leader(name: "Volodymyr Zelensky", age: 45, DOB: "25/01/1978", country: "Ukraine", position: "President", description: "Volodymyr Oleksandrovych Zelenskyy is a Ukrainian politician and former comedian and actor who is the sixth and current president of Ukraine since 2019. Born to a Ukrainian Jewish family, Zelenskyy grew up as a native Russian speaker in Kryvyi Rih, a major city of Dnipropetrovsk Oblast in central Ukraine.", imageName: "volodymyr-zelensky", locationCoordinate: CLLocationCoordinate2D(latitude: 50.446836,  longitude: 30.530311)),
    
    Leader(name: "Xi JinPing", age: 70, DOB: "15/06/1953", country: "China", position: "President", description: "Xi Jinping is a Chinese politician who has been serving as the general secretary of the Chinese Communist Party, chairman of the Central Military Commission and the president of the People's Republic of China. He is current and the fifth paramount leader of China since its foundation in 1949.", imageName: "xi_jinping", locationCoordinate: CLLocationCoordinate2D(latitude: 39.911389,  longitude: 116.380556)),
    
    Leader(name: "Yoon Suk Yeol", age: 62, DOB: "18/12/1960", country: "South Korea", position: "President", description: "Yoon Suk Yeol is a South Korean politician who has been serving as the 13th and current president of South Korea since 2022. Prior to his presidency, he served as the prosecutor general of South Korea between 2019 and 2021. Born in Seoul, Yoon attended Seoul National University.", imageName: "yoon_suk_yeol", locationCoordinate: CLLocationCoordinate2D(latitude: 37.586673,  longitude: 126.976268))
    
]
